apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Backstage.v1alpha1.rhdh.redhat.com
  name: rhdh-operator
  namespace: rhdh-operator
spec:
  upgradeStrategy: Default
